import { ApiError } from './errors.js';

export const emptyRegistry = () => ({
  schemaVersion: 1, owners: {}, companies: {}, memberships: {},
  sessions: {}, oauth: {}, registrations: {},
});

// Callbacks must be synchronous and side-effect free: CAS retries rerun them.
// Random IDs/tokens are generated by callers before entering a transaction.
export class Registry {
  constructor(adapter, { now = Date.now } = {}) { this.adapter = adapter; this.now = now; }
  async read() {
    const snapshot = await this.adapter.read();
    if (snapshot.state.schemaVersion !== 1) throw new Error('Unsupported control registry version');
    return snapshot;
  }
  async transact(update) {
    for (let attempt = 0; attempt < 12; attempt++) {
      const { state, generation } = await this.read();
      for (const collection of [state.sessions, state.oauth]) {
        for (const [key, value] of Object.entries(collection)) {
          if (value.expiresAt <= this.now()) delete collection[key];
        }
      }
      const result = update(state);
      if (result instanceof Promise) throw new Error('Registry transaction callbacks cannot perform I/O');
      if (Buffer.byteLength(JSON.stringify(state)) > 8 * 1024 * 1024) {
        throw new ApiError(503, 'REGISTRY_CAPACITY', 'Service capacity reached. Please contact support.');
      }
      if (await this.adapter.compareAndSwap(generation, state)) return result;
      await new Promise(resolve => setTimeout(resolve, Math.min(100, 2 ** attempt) + Math.random() * 10));
    }
    throw new ApiError(503, 'RETRY_REQUIRED', 'The service is busy. Retry this operation with the same idempotency key.');
  }
}
